name: secret-scan
on:
  push:
    branches:
      - dev
      - main
      - development
  pull_request:
    branches:
      - dev
      - main
      - development
  
  workflow_dispatch:

jobs:
  find-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Accuknox Secret Scan
        uses: accuknox/secret-scan-action@v1.0.0 
        with:
          endpoint: ${{ secrets.CSPM_ENDPOINT }}
          tenant_id: ${{ secrets.TENANT_ID }}
          label: ${{ secrets.LABEL_ID }}
          token: ${{ secrets.CSPM_TOKEN }}
          fail: "false"
